### ISSUE TITLE
Upgrade vnu

### ISSUE THREAD

**Issue by jyasskin** [w3c/spec-prod#188]
https://github.com/w3ctag/privacy-principles/actions/runs/11097000177/job/30827581027?pr=443 installed vnu 23.4.11 and complained that CSS using `:has` is invalid:

```css
    ul:has(#include-websites) li { list-style:none }

    /* Show summary principles if their audience is selected. */
    #bp-summary li:has(.practicelab) { display: none }
    #bp-summary ul:has(#include-websites:checked) + #best-practices-summary li:has(.audience-websites) { display: list-item; }
    #bp-summary ul:has(#include-user-agents:checked) + #best-practices-summary li:has(.audience-user-agents) { display: list-item; }
    #bp-summary ul:has(#include-api-designers:checked) + #best-practices-summary li:has(.audience-api-designers) { display: list-item; }
```

The version at https://validator.w3.org/nu/?doc=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2Fjyasskin%2Fprivacy-principles%2Fpull%2F443.html is 24.9.28 and doesn't complain about this CSS syntax.
