### ISSUE TITLE
Multiple input sources

### ISSUE THREAD

**Issue by reillyeon** [w3c/spec-prod#31]
Some specifications, such as [WebUSB](https://github.com/wicg/webusb) and [Web Bluetooth](https://github.com/webbluetoothcg/web-bluetooth) have multiple Bikeshed documents.

**Comment by xfq** [comment]
Other examples:

* https://github.com/w3c/csswg-drafts (Bikeshed)
* https://github.com/w3c/epub-specs/ (ReSpec)
* https://github.com/w3c/iip/ (ReSpec)

**Comment by sidvishnoi** [comment]
Supporting build/validate/deploy of multiple sources within the action will require major work.

I think we can add a config option `DESTINATION`, corresponding to `SOURCE`. Then the action can be called multiple times with different SOURCE/DESTINATION pairs, like:
```yml
runs-on: ubuntu-20.04
steps:
  - uses: actions/checkout
  - uses: w3c/spec-prod@v2
    with:
      SOURCE: specs/spec1/index.bs
      DESTINATION: spec1/index.html
      # other-inputs...
  - uses: w3c/spec-prod@v2
    with:
      SOURCE: specs/spec2/index.bs
      DESTINATION: spec2/
      # other-inputs...
```

It's a bit cumbersome if there are many specs, but it's one-time config.

It might be possible to reduce the boilerplate (with an added advantage of parallelism):
```yml
runs-on: ubuntu-20.04
strategy:
  matrix:
    include:
      - source: specs/spec1/index.bs
        destination: spec1/
      - source: specs/spec2/spec.bs
        destination: spec2/
steps:
  - uses: actions/checkout
  - uses: w3c/spec-prod@v2
    with:
      SOURCE: ${{ matrix.source }}
      DESTINATION: ${{ matrix.destination }}
      # other-inputs...
```

Notes to self:
- Each call to `spec-prod` will need clean-up after itself. 
- Avoid race conditions when deploying to GitHub pages (maybe `pull --rebase` right before `push --force-with-lease` can help)
