### ISSUE TITLE
Multi-spec repositories, Echidna tokens and build overrides

### ISSUE THREAD

**Issue by tidoust** [w3c/spec-prod#55]
I haven't tried it yet but I'm surprised that multi-spec repositories support actually works [as documented](https://github.com/w3c/spec-prod/blob/main/docs/examples.md#multiple-specs-in-same-repository). Aren't [Echidna tokens per spec](https://github.com/w3c/echidna/wiki/Token-creation)? Cc @deniak

Also, `GH_PAGES_BUILD_OVERRIDE` and `W3C_BUILD_OVERRIDE` are typically settings that one would want to set on individual specs, and the use of a source/destination matrix for multi-spec repositories does not seem to allow that. For instance, a repo could contain a spec that needs to be published as WD and a spec that needs to be published as CRD.

All of the above can be solved by using the [workaround that separates worfklows](https://github.com/w3c/spec-prod/blob/main/docs/examples.md#multiple-specs-in-same-repository). I'm wondering whether that could be the _right way_ to do it in practice (a tad verbose perhaps), and not only a _workaround_...

**Comment by sidvishnoi** [comment]
I think my attempt to keep the example short might have made it a bit misleading. Following is a more complete example:
```yaml
name: CI
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - source: spec.html
            destination: index.html
            echidna-token: ${{ secrets.ECHIDNA_TOKEN }}
          - source: spec-1
            destination: the-spec
            echidna-token: ${{ secrets.ECHIDNA_TOKEN_SPEC_1 }}
          - source: spec-2
            # destination defaults to spec-2/index.html
            echidna-token: ${{ secrets.ECHIDNA_TOKEN_SPEC_2 }}
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: ${{ matrix.source }}
          DESTINATION: ${{ matrix.destination }}
          GH_PAGES_BRANCH: gh-pages
          W3C_ECHIDNA_TOKEN: ${{ matrix.echidna-token }}
          W3C_WG_DECISION_URL: "https://lists.w3.org/Archives/Public/xyz.html"
```

`W3C_WG_DECISION_URL`, `GH_PAGES_BUILD_OVERRIDE`, `W3C_BUILD_OVERRIDE` etc. can also be specified via the strategy matrix, if needed.

IIRC, GitHub Actions also support an "or" operation, so we can have defaults like:
`W3C_ECHIDNA_TOKEN: ${{ matrix.echidna-token || secrets.DEFAULT_ECHIDNA_TOKEN }}`

> using the workaround that separates workflows.

I think that would depend on how many specs there are, and how many custom options the workflow needs. Both are _right ways_ to do things, and are supported by the action.

Primary concern with separate workflows is maintenance (like updating version in `uses: w3c/spec-prod@v2` across multiple files, instead of one place; repetition and manual `on.<push|pull_request>.paths`). Might be worth trying it in practice to check what works better for multi-spec repos.
